name: evodiff
channels:
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - python=3.8.5
  - pandas
  - numpy
  - python-lmdb
  - pip
  - pip:
      - git+https://github.com/microsoft/protein-sequence-models.git
      - scikit-learn
      - seaborn
      - blosum
      - matplotlib
      - fair-esm
      - biotite
      - tqdm
      - git+https://github.com/HeliXonProtein/OmegaFold.git
      - mdanalysis
      - pdb-tools
